CREATE TABLE TEST01.TBL_PROD_INFMAPP
(
    FA_ID       VARCHAR2(50),
    LT_ID       VARCHAR2(50),
    PROD_ID     VARCHAR2(50) ,
    MAIN_PROD_ID  VARCHAR2(50),
    PROD_YN       VARCHAR2(10)
);

CREATE UNIQUE INDEX TEST01.TBL_PROD_INFMAPP_PK
ON TEST01.TBL_PROD_INFMAPP(FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST01.TBL_PROD_INFMAPP ADD CONSTRAINT TBL_PROD_INFMAPP_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID);



INSERT INTO TEST01.TBL_PROD_INFMAPP
SELECT FA_ID
     , LT_ID
     , PROD_ID
     , PROD_ID || '_MAIN'
     , CASE WHEN MOD(ROWNUM, 2)  = 1 THEN 'Y'
     ELSE 'N'
     END AS PROD_YN
  FROM TEST01.TBL_LT_INF
 WHERE ROWNUM <= 5000
  ;
  
INSERT INTO TEST01.TBL_PROD_INFMAPP
SELECT FA_ID
     , LT_ID
     , PROD_ID
     , PROD_ID || '_MAIN'
     , CASE WHEN MOD(ROWNUM, 3)  = 1 THEN 'Y'
     ELSE 'N'
     END AS PROD_YN
  FROM TEST02.TBL_LT_INF
 WHERE ROWNUM <= 10000
  ;
  
COMMIT;
  

-- 여기부터
SELECT *
FROM (
  SELECT A.FA_ID,
        A.LT_ID,
        NVL(B.PROD_ID_MAIN, A.PROD_ID) PROD_ID,
        A.FL_ID,
        A.OP_ID,
        A.TIMEKEY,
        A.CHG_TM,
        A.CRT_TM
  FROM TEST01.TBL_LT_INF A
      ,TEST01.TBL_PROD_INFMAPP B
  WHERE A.FA_ID(+) = B.FA_ID 
  AND A.LT_ID(+) = B.LT_ID 
  AND A.PROD_ID(+) = B.PROD_ID
  AND B.PROD_YN = 'Y';
)

UNION ALL
-- 밑부터 모르겟어...ㅠ_ㅠ